<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        @page { margin: 24px 26px; }
        body {
            font-family: Arial, Helvetica, sans-serif;
            font-size: 11px;
            color: #111827;
            line-height: 1.45;
        }
        .sheet {
            border: 1px solid #d1d5db;
            padding: 16px;
        }
        .header {
            border-bottom: 2px solid #111827;
            padding-bottom: 10px;
            margin-bottom: 10px;
        }
        .title {
            font-size: 18px;
            font-weight: 700;
            margin-bottom: 2px;
        }
        .subtitle {
            font-size: 12px;
            color: #374151;
            margin-bottom: 8px;
        }
        .meta {
            font-size: 11px;
            color: #374151;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 8px;
        }
        th,
        td {
            border: 1px solid #d1d5db;
            padding: 7px 8px;
            text-align: left;
            vertical-align: top;
        }
        th {
            background: #f3f4f6;
            font-size: 10px;
            text-transform: uppercase;
            letter-spacing: 0.04em;
        }
        .amount {
            font-weight: 700;
            white-space: nowrap;
        }
        .muted {
            color: #6b7280;
        }
        .footer {
            margin-top: 10px;
            font-size: 10px;
            color: #6b7280;
            text-align: right;
        }
    </style>
</head>
<body>
    <div class="sheet">
        <div class="header">
            <div class="title">EBA Information System</div>
            <div class="subtitle">Concessionaire Payment History Report</div>
            <div class="meta">Concessionaire: {{ $concessionaire->name ?: 'N/A' }}</div>
            <div class="meta">Business Name: {{ $concessionaire->business_name ?: 'N/A' }}</div>
            <div class="meta">Generated: {{ $generatedAt->format('M d, Y h:i A') }}</div>
        </div>

        <table>
            <thead>
                <tr>
                    <th>Amount Paid (PHP)</th>
                    <th>Payment Date</th>
                    <th>Payment Type</th>
                    <th>Recorded By</th>
                    <th>Recorded At</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($payments as $payment)
                    <tr>
                        <td class="amount">PHP {{ number_format((float) $payment->amount, 2) }}</td>
                        <td>{{ $payment->payment_date?->format('M d, Y') ?? 'N/A' }}</td>
                        <td>{{ ucfirst(str_replace('_', ' ', (string) $payment->payment_type)) }}</td>
                        <td>{{ $payment->recordedBy?->name ?: 'N/A' }}</td>
                        <td>{{ $payment->created_at?->setTimezone('Asia/Manila')->format('M d, Y h:i A') ?? 'N/A' }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="5" class="muted">No payment records found for this concessionaire.</td>
                    </tr>
                @endforelse
            </tbody>
        </table>

        <div class="footer">Generated by EBA Cashier Panel</div>
    </div>
</body>
</html>
